using Methods_Exercise_2;
Console.WriteLine("Add:");
Console.WriteLine(Method.OperatorAdd(2,2));
Console.WriteLine("Substract:");
Console.WriteLine(Method.OperatorSubstract(2, 2));
Console.WriteLine("Multiply:");
Console.WriteLine(Method.OperatorMultiply(2, 2));
Console.WriteLine("Devide:");
Console.WriteLine(Method.OperatorDevide(2, 2));
Console.WriteLine("Modulus:");
Console.WriteLine(Method.OperatorModulo(3,2));
Console.WriteLine("Params:");
Console.WriteLine(Method.OperatorSum(4,77,34,987,2,4,5,6));